### ISSUE TITLE
Please provide some more info on TICCL-anahash parameter --background

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#20]
Concerning TICCL-anahash:

The usage tells me: "When a background corpus is specified, we also produce a new (merged) frequency file.".

So: what will this new file's file name be?

Also: Should the rest of the suite of TICCL tools then use this newly created frequency file rather than the clean *tsv one produced by TICCL-unk?

Thank you!

**Comment by kosloot** [comment]
The proof of the pudding is in the eating :)
When you use the --background option, the program will tell you:
``stored merged corpus in ``
followed by a filename composed of the input filename with ``.merged`` appended.

If this file is suitable for further usage is unclear. But i assume so, otherwise there is little use for this procedure.

**Comment by kosloot** [comment]
closing due to lack of feedback
